# This workflow is intended to check if PR conforms with coding standards used
# in the project.
#
# Documentation for GitHub Actions:
# [workflow-syntax]: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
# [context-and-expression-syntax]: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
# [workflow-commands]: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions

name: Check code style

on:
  pull_request:
    branches:
      - main
      - llvm_release_*
    paths-ignore: # no need to check formatting for:
      - 'docs/**' # documentation
      - 'test/**' # tests
      - '**.md'   # README
      - '**.txt'  # CMakeLists.txt
      - '**/check-**-build.yml' # build workflows
      - '**/backport-to-branch.yml' # backport workflow
      - '**/patch-release.yaml' # patch release workflow
  repository_dispatch:
    types: [backport-complete]
    branches:
      - main
      - llvm_release_*
    paths-ignore: # no need to check formatting for:
      - 'docs/**' # documentation
      - 'test/**' # tests
      - '**.md'   # README
      - '**.txt'  # CMakeLists.txt
      - '**/check-**-build.yml' # build workflows
      - '**/backport-to-branch.yml' # backport workflow
      - '**/patch-release.yaml' # patch release workflow

env:
  # We need compile command database in order to perform clang-tidy check. So,
  # in order to perform configure step we need to setup llvm-dev package. This
  # env variable used to specify desired version of it
  LLVM_VERSION: 24

permissions:
  contents: read

jobs:
  clang-format-and-tidy:
    name: clang-format & clang-tidy
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout sources
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        # In order to gather diff from PR we need to fetch not only the latest
        # commit. Depth of 2 is enough, because GitHub Actions supply us with
        # merge commit as {{ github.sha }}, i.e. the second commit is a merge
        # base between target branch and PR
        persist-credentials: false
        fetch-depth: 2

    - name: Gather list of changes
      id: gather-list-of-changes
      run: |
        git diff -U0 --no-color "${GITHUB_SHA}"^ -- include lib \
            ':(exclude)include/LLVMSPIRVExtensions.inc' \
            ':(exclude)lib/SPIRV/libSPIRV/SPIRVErrorEnum.h' \
            ':(exclude)lib/SPIRV/libSPIRV/SPIRVOpCodeEnum.h' \
            ':(exclude)lib/SPIRV/libSPIRV/SPIRVOpCodeEnumInternal.h' \
            > diff-to-inspect.txt
        if [ -s diff-to-inspect.txt ]; then
          # Here we set an output of our step, which is used later to either
          # perform or skip further steps, i.e. there is no sense to install
          # clang-format if PR hasn't changed .cpp files at all
          # See [workflow-commands] for reference
          echo 'HAS_CHANGES=true' >> "$GITHUB_OUTPUT"
        fi
    - name: Install dependencies
      if: ${{ steps.gather-list-of-changes.outputs.HAS_CHANGES }}
      run: |
        # clang-tidy requires compile command database in order to be properly
        # launched, so, we need to setup llvm package to perform cmake
        # configuration step to generate that database
        curl -L "https://apt.llvm.org/llvm-snapshot.gpg.key" | sudo apt-key add -
        echo "deb https://apt.llvm.org/noble/ llvm-toolchain-noble main" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install -yqq \
            clang-format-"${LLVM_VERSION}" clang-tidy-"${LLVM_VERSION}" \
            clang-tools-"${LLVM_VERSION}" llvm-"${LLVM_VERSION}"-dev \
            libomp-"${LLVM_VERSION}"-dev libllvmlibc-"${LLVM_VERSION}"-dev \
            mlir-"${LLVM_VERSION}"-tools libpolly-"${LLVM_VERSION}"-dev \
    - name: Generate compile command database
      if: ${{ steps.gather-list-of-changes.outputs.HAS_CHANGES }}
      run: |
        mkdir build && cd build
        cmake -DCMAKE_CXX_COMPILER=clang++-"${LLVM_VERSION}" \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" "${GITHUB_WORKSPACE}"
    - name: Run clang-format
      if: ${{ steps.gather-list-of-changes.outputs.HAS_CHANGES }}
      id: run-clang-format
      run: |
        cat diff-to-inspect.txt | /usr/share/clang/clang-format-"${LLVM_VERSION}"/clang-format-diff.py \
            -p1 -binary clang-format-"${LLVM_VERSION}"
    - name: Run clang-tidy
      # By some reason, GitHub Actions automatically include "success()"
      # expression into an "if" statement if it doesn't contain any of job
      # status check functions. This is why this and following steps has
      # "always()" and "failure()" in "if" conditions.
      # See "Job status check functions" in [context-and-expression-syntax]
      if: ${{ always() && steps.gather-list-of-changes.outputs.HAS_CHANGES }}
      id: run-clang-tidy
      run: |
        cat diff-to-inspect.txt | /usr/lib/llvm-"${LLVM_VERSION}"/share/clang/clang-tidy-diff.py \
            -p1 -clang-tidy-binary clang-tidy-"${LLVM_VERSION}" -quiet \
            -path "${GITHUB_WORKSPACE}"/build
    - name: Upload patch with clang-format fixes
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: ${{ failure() && steps.run-clang-format.outcome == 'failure' }}
      with:
        name: clang-format.patch
        path: clang-format.patch
        if-no-files-found: ignore

    - name: Upload clang-tidy log
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: ${{ failure() && steps.run-clang-tidy.outcome == 'failure' }}
      with:
        name: clang-tidy.log
        path: clang-tidy.log
        if-no-files-found: ignore
