name: Compiler CI PSDB trigger on spirv-llvm-translator amd-staging branch

# Controls when the workflow will run
on:
  pull_request:
    branches: [amd-staging]
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel, below is a single job called invoke jenkins jobs
permissions:
  contents: read

jobs:
  # This workflow contains a single job called "invoke_jenkins_PSDB"
  invoke_jenkins_PSDB:
    if: github.event.pull_request.draft == false
    runs-on:
      group: compiler-generic-runners
    env:
        svc_acc_org_secret: ${{secrets.CI_GITHUB_TOKEN}}
        input_sha: ${{ github.event.pull_request.head.sha != '' && github.event.pull_request.head.sha || github.sha }}
        input_pr_num: ${{ github.event.pull_request.number != '' && github.event.pull_request.number || 0 }}
        input_pr_url: ${{ github.event.pull_request.html_url != '' && github.event.pull_request.html_url || '' }}
        PR_TITLE: ${{ github.event.pull_request.title != '' && github.event.pull_request.title || '' }}
        # set the pipeline name here based on branch name
        pipeline_name:  ${{secrets.CI_JENKINS_JOB_NAME}}
        JENKINS_URL: ${{secrets.CI_JENKINS_URL}}
        CONTAINER_NAME: my_container_${{ github.run_id }}
        CONTAINER_IMAGE: ${{ secrets.JENKINS_TRIGGER_DOCKER_IMAGE }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Pull container image
        run: |
          docker pull "${CONTAINER_IMAGE}"



      - name: Run container
        run: |
          docker run -d --name "$CONTAINER_NAME" "$CONTAINER_IMAGE" sleep infinity
          docker exec "${CONTAINER_NAME}" /bin/bash -c "echo 'Running commands inside the container'"
      - name: Run Jenkins Cancel Script
        env:
          JENKINS_URL: ${{secrets.CI_JENKINS_URL}}
          JENKINS_USER:  ${{secrets.CI_JENKINS_USER}}
          JENKINS_API_TOKEN: ${{secrets.CI_JENKINS_TOKEN}}
          JENKINS_JOB_NAME: ${{secrets.CI_JENKINS_JOB_NAME}}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          COMMIT_HASH: ${{ github.event.after }}
        run: |
          docker exec -e JENKINS_JOB_NAME -e PR_NUMBER -e COMMIT_HASH \
            -e JENKINS_URL -e JENKINS_USER -e JENKINS_API_TOKEN \
            "$CONTAINER_NAME" python3 cancel_previous_build.py


      - name: Getting Event Details
        run: |
          jq '{action, number, pull_request: (.pull_request |
            {id, html_url, number, head: .head.sha, base: .base.ref})}' "$GITHUB_EVENT_PATH"

      - name: Trigger Jenkins Pipeline
        run: |
          echo "--Running jenkins_api.py with input sha - $input_sha for pull request - $input_pr_url"
          docker exec -e GITHUB_REPOSITORY="$GITHUB_REPOSITORY" -e svc_acc_org_secret="$svc_acc_org_secret" -e input_sha="$input_sha" -e input_pr_url="$input_pr_url" -e pipeline_name="$pipeline_name" \
                     -e input_pr_num="$input_pr_num" -e PR_TITLE="$PR_TITLE" -e JENKINS_URL="$JENKINS_URL" -e GITHUB_PAT="$svc_acc_org_secret" "${CONTAINER_NAME}"  \
                     /bin/bash -c 'echo \"PR NUM: "$input_pr_num"\" && python3 jenkins_api.py -s \"${JENKINS_URL}\" -jn "$pipeline_name" -ghr "$GITHUB_REPOSITORY" -ghsha "$input_sha" -ghprn "$input_pr_num" -ghpru "$input_pr_url" -ghprt "$PR_TITLE" -ghpat="$svc_acc_org_secret"'
      - name: Stop and remove container
        if: always()
        run: |
          docker stop "${CONTAINER_NAME}"
          docker rm "${CONTAINER_NAME}"
